version: "3"
networks:
  gitea:
    external: false
services:
  server:
    image: gitea/gitea:1.15.0
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=db:5432
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=gitea
    restart: always
    networks:
      - gitea
    volumes:
      - ./volumes/gitea:/data
      - ~/.ssh:/data/git/.ssh
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "222:22"
    depends_on:
      - db
  db:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_USER=gitea
      - POSTGRES_PASSWORD=gitea
      - POSTGRES_DB=gitea
    networks:
      - gitea
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
  mosquitto:
    networks:
      - gitea
    image: eclipse-mosquitto:2.0
    volumes:
      - ./volumes/srv/mqtt/data:/mosquitto/data
      - ./volumes/srv/mqtt/log:/mosquitto/log
      - ./configs/mosquitto_config:/mosquitto/config/mosquitto.conf
      - ./configs/passwords.txt:/mosquitto/config/passwd_file
    ports:
      - "11883:1883"
      - "18883:8883"

  gitea-listener:
    networks:
      - gitea
    image: gitea-listener:latest
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      GITEA_LISTENER_CONFIG_FILE: /code/gl_config.yaml
    command: "bash -c 'source env/bin/activate && uvicorn --host 0.0.0.0
          gitea_listener.app:app'"
    restart: on-failure
    ports:
      - "9000:8000"
    volumes:
      - ./configs/gitea_listener_config.yaml:/code/gl_config.yaml
    depends_on:
      - mosquitto
