version: "2.4"
services:
  mosquitto:
    image: eclipse-mosquitto:2.0
    volumes:
      - ../data/gitea_listener/mosquito/data:/mosquitto/data
      - ../data/gitea_listener/mosquito/log:/mosquitto/log
      - ./configs/mosquitto_config:/mosquitto/config/mosquitto.conf
    ports:
      - "11883:1883"

  gitea-listener:
    image: gitea-listener:latest
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      GITEA_LISTENER_CONFIG_FILE: /code/gl_config.yaml
    command: "bash -c 'source env/bin/activate && uvicorn --host 0.0.0.0
          gitea_listener.app:app'"
    restart: on-failure
    ports:
      - "9000:8000"
    volumes:
      - ./configs/gitea_listener_config.yaml:/code/gl_config.yaml
    depends_on:
      - mosquitto
